### ISSUE TITLE
Define 'low dimensional' in README.txt

### ISSUE THREAD

**Issue by bmschmidt** [TutteInstitute/fast_hdbscan#2]
Exciting project, thanks for sharing! I wonder if in the readme.txt you could put some broad numbers on what you mean by this being optimized for 'low dimensional data.' Sometimes I see people use that to mean 2-4 dimensions, sometimes up to 128 or beyond--would help in thinking about where I might use this.

**Comment by lmcinnes** [comment]
Good point. I have clarified the README with some more precise numbers. Right now it is built with KD-Trees so only really handles KD-Tree style workloads. In the future I may add other indexes that support higher dimensions better.

**Comment by bmschmidt** [comment]
Thank you!
