### ISSUE TITLE
feature request: specify max number of threads

### ISSUE THREAD

**Issue by Zheludev** [TutteInstitute/fast_hdbscan#23]
fast_hdbscan is awesome!

Is there a way to specify the max number of threads to use (vs the default 'all' it seems to use)? and if not, could such a feature please be added?

thanks!

Ivan

**Comment by lmcinnes** [comment]
There isn't a built-in option, but if you do:

```python
import numba
numba.set_num_threads(8)
```

prior to running fast_hdbscan it will restrict to using 8 parallel threads -- or whatever number you choose to set.

**Comment by Zheludev** [comment]
thanks!
